config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  post '/update_location', to: 'application#update_location'
  root to:"tops#top"
  get 'top', to: 'tops#top'  # /topへのルーティングを追加

  resources :signs, only: [:index, :show]
  resources :planets, only: [:index, :show]
  resources :fortunes, only: [:index, :show]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def update_location
    session[:latitude] = params[:latitude]
    session[:longitude] = params[:longitude]
    head :ok
  end
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  require 'faraday'
  require 'json'

  def index
    data = Time.now.strftime("%Y/%m/%d")

    conn = Faraday.new(url: "http://api.jugemkey.jp/api/horoscope/free/#{data}")
    response = conn.get

    @data = JSON.parse(response.body)
  end

  def show
    data = Time.now.strftime("%Y/%m/%d")
    @sign = params[:id]
  
    conn = Faraday.new(url: "http://api.jugemkey.jp/api/horoscope/free/#{data}")
    response = conn.get
  
    @data = JSON.parse(response.body)
    @horoscope = @data['horoscope'][data].find { |h| h['sign'] == @sign }
  end

end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  require 'faraday'
  require 'json'

  def index
    # 現在の日時を取得
    current_time = Time.now

    lat = session[:latitude] || '35.6581'  # デフォルト値を設定
    lng = session[:longitude] || '139.7414'  # デフォルト値を設定

    # Bearer 
    token = ENV['BEARER_TOKEN']

    # 惑星の情報を取得
    planets_conn = Faraday.new(url: 'https://app.livlog.xyz/hoshimiru/planet') do |faraday|
      faraday.request  :url_encoded
      faraday.response :logger
      faraday.adapter  Faraday.default_adapter
      faraday.headers['Authorization'] = "Bearer #{token}"
      faraday.headers['Accept'] = 'application/json'
    end

    planets_response = planets_conn.get do |req|
      req.url '', { lat: lat, lng: lng, date: current_time.strftime('%Y-%m-%d'), hour: current_time.strftime('%H'), min: current_time.strftime('%M'), disp:"on" }
    end

    @planets_data = JSON.parse(planets_response.body)    
  end

  def show
    # 現在の日時を取得
    current_time = Time.now

    lat = session[:latitude] || '35.6581'  # デフォルト値を設定
    lng = session[:longitude] || '139.7414'  # デフォルト値を設定

    # Bearer 
    token = ENV['BEARER_TOKEN']

    # 惑星の情報を取得
    planets_conn = Faraday.new(url: 'https://app.livlog.xyz/hoshimiru/planet') do |faraday|
      faraday.request  :url_encoded
      faraday.response :logger
      faraday.adapter  Faraday.default_adapter
      faraday.headers['Authorization'] = "Bearer #{token}"
      faraday.headers['Accept'] = 'application/json'
    end

    planets_response = planets_conn.get do |req|
      req.url '', { lat: lat, lng: lng, date: current_time.strftime('%Y-%m-%d'), hour: current_time.strftime('%H'), min: current_time.strftime('%M'), id: params[:id], disp:"on" }
    end

    @planets_data = JSON.parse(planets_response.body)    
  end
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  require 'faraday' # Faradayを使用する場合
  require 'json'

  def index
    # Bearer 
    token = ENV['BEARER_TOKEN']

    current_time = Time.now

    lat = session[:latitude] || '35.6581'  # デフォルト値を設定
    lng = session[:longitude] || '139.7414'  # デフォルト値を設定

    # Faradayのインスタンスを作成
    conn = Faraday.new(url: 'https://app.livlog.xyz/hoshimiru/constellation')

    # リクエストヘッダーに認証情報を含める
    conn.headers['Authorization'] = "Bearer #{token}"
    conn.headers['Accept'] = 'application/json'

    # APIエンドポイントにリクエストを送信
    response = conn.get do |req|
      req.url '', { lat: lat, lng: lng, date: current_time.strftime('%Y-%m-%d'), hour: current_time.strftime('%H'), min: current_time.strftime('%M'), disp:"on" }
    end

    # レスポンスを解析
    data = JSON.parse(response.body)

      # 検索クエリに基づいてフィルタリング
    if params[:search].present?
      @data = data['results'].select { |result| result['jpName'].include?(params[:search])|| result['enName'].include?(params[:search])|| result['ryaku'].include?(params[:search])|| result['season'].include?(params[:search])|| result['direction'].include?(params[:search])|| result['altitude'].include?(params[:search])|| result['content'].include?(params[:search])|| result['origin'].include?(params[:search])}
    else
      @data = data['results']
    end
  end

  def show
    # Bearer 
    token = ENV['BEARER_TOKEN']

    current_time = Time.now

    lat = session[:latitude] || '35.6581'  # デフォルト値を設定
    lng = session[:longitude] || '139.7414'  # デフォルト値を設定

    # Faradayのインスタンスを作成
    conn = Faraday.new(url: 'https://app.livlog.xyz/hoshimiru/constellation')

    # リクエストヘッダーに認証情報を含める
    conn.headers['Authorization'] = "Bearer #{token}"
    conn.headers['Accept'] = 'application/json'

    # APIエンドポイントにリクエストを送信
    response = conn.get do |req|
      req.url '', { lat: lat, lng: lng, date: current_time.strftime('%Y-%m-%d'), hour: current_time.strftime('%H'), min: current_time.strftime('%M'), id: params[:id], disp:"on" }
    end

    # レスポンスを解析
    @data = JSON.parse(response.body)
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def top
    require 'faraday'
    require 'json'

    token = ENV['BEARER_TOKEN']
    # 現在の日時を取得
    current_time = Time.now

    lat = session[:latitude] || '35.6581'  # デフォルト値を設定
    lng = session[:longitude] || '139.7414'  # デフォルト値を設定

    # 星座の情報を取得
    conn = Faraday.new(url: 'https://app.livlog.xyz/hoshimiru/constellation') do |faraday|
      faraday.request  :url_encoded
      faraday.response :logger
      faraday.adapter  Faraday.default_adapter
      faraday.headers['Authorization'] = "Bearer #{token}"
      faraday.headers['Accept'] = 'application/json'
    end

    response = conn.get do |req|
      req.url '', { lat: lat, lng: lng, date: current_time.strftime('%Y-%m-%d'), hour: current_time.strftime('%H'), min: current_time.strftime('%M'), disp:"off" }
    end

    @data = JSON.parse(response.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signs_helper.rb
module SignsHelper
end

app/views/fortunes/index.html.erb
<div class="fortune_containar">
  <div class="fortune_titles">
    <h2><i class="material-icons-outlined">auto_awesome_motion</i>本日の運勢占い</h2>
  </div>

  <div class="fortune_index">
    <% @data['horoscope'][Time.now.strftime("%Y/%m/%d")].each do |horoscope| %>
      <p><%= image_tag "#{horoscope['sign']}.png", class: "fortune_image" %> <%= link_to horoscope['sign'], fortune_path(horoscope['sign']), class: "index-menu-link startButton" %></p>
    <% end %>
  </div>
</div>

app/views/fortunes/show.html.erb
<div class="fortune_result_container">
  <div class="fortune_result">
    <h1><%= image_tag "#{@sign}.png", class:"fortune_result_image" %><%= @sign %>の占い結果</h1>
    <% if @horoscope['rank']!=12 %>
      <h2>第<%= @horoscope['rank'] %>位です。</h2>
    <% else %>
      <h2>最下位です…(:_;)</h2>
    <% end %>
    <h4><%= @horoscope['content'] %></h4>
    <p>【ラッキーアイテム】<%= @horoscope['item'] %></p>
    <p>【ラッキーカラー】<%= @horoscope['color'] %></p>
    <p>【総合運】<%= "☆" * @horoscope['total'] %></p>
    <p>【金運】<%= "☆" * @horoscope['money'] %></p>
    <p>【仕事運】<%= "☆" * @horoscope['job'] %></p>
    <p>【恋愛運】<%= "☆" * @horoscope['love'] %></p>
  </div>
  
  <div class="twitter_share_container">
    <%= link_to "https://twitter.com/share?url=#{request.url}", target: '_blank', class: "twitter_share" do %>
      <i class="fa-brands fa-square-x-twitter"></i>結果をXでシェア
    <%end%>
    <%= link_to '戻る', request.referrer, class: "wiki_link startButton" %>
  </div>
</div>

<script>
document.querySelector('.twitter_share').addEventListener('click', function(e) {
  e.preventDefault();
  const sign = '<%= @sign %>';
  const rank = '<%= @horoscope['rank'] %>';
  const content = '<%= @horoscope['content'] %>';
  const item = '<%= @horoscope['item'] %>';
  const color = '<%= @horoscope['color'] %>';
  const siteUrl = '<%= "https://sign-dxuu.onrender.com/fortunes" %>'
  const tweet = encodeURIComponent(
    sign + "の今日の運勢\n" 
    + (rank !=="12" ? "第" + rank + "位\n" : "最下位\n")
    + content + "\nラッキーアイテム: " 
    + item + "\nラッキーカラー: "
    + color + "\n"
    + siteUrl
    );
  const url = 'https://twitter.com/intent/tweet?text=' + tweet;
  window.open(url, '_blank');
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>星の図鑑</title>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="csrf-token" content="<%= form_authenticity_token %>">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    <script src="https://kit.fontawesome.com/db12d6f744.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    
    <header>
      <%= render "shared/header" %>
    </header>
    
    <main>
      <div id="content">

        <%= image_tag '星(大).png', class: 'shooting-bigstar star' %>
        <%= image_tag '星(中).png', class: 'shooting-middlestar star' %>
        <%= image_tag '星(小).png', class: 'shooting-smallstar star' %>

        <%= yield %>

      </div>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>
  
  </body>

</html>

app/views/planets/index.html.erb
<div class="planets_containar">
  <div class="planets_title">
    <h2><i class="material-icons-outlined">rocket</i>惑星一覧</h2>
  </div>

  <div class="planets_index">
    <% @planets_data['results'].each do |object| %>
      <p><%= link_to object['jpName'], planet_path(object['id']), class: "index-menu-link startButton" %></p>
    <% end %>
  </div>
</div>

app/views/planets/show.html.erb
<div class="planet_detail">
  <% @planets_data['results'].each do |object| %>
    <div class="planet_info">
      <div class="text_content">
        <div class="text_upper_part">
          <div class="text_upper_part_name">
            <h1><%= object['jpName'] %><span></h1>
            <h3><%= object['enName'] %></h3>
          </div>
            <h4>【方角】 <%= object['direction'] %></h4>
            <h4>【高度】 <%= object['altitude'] %></h4>
            <p>※「水平線の下」と表示されている場合、現在観測できません。</p>
        </div>
        <div class="text_beneath">
          <p><%= object['content'] %></p>
          <h4>【神話】</h4>
          <p><%= object['origin'] %></p>
        </div>
        <%= link_to "wiki", "https://ja.wikipedia.org/wiki/#{object['jpName']}", class: "wiki_link" %>
        <%= link_to '戻る', request.referrer, class: "wiki_link startButton" %>
      </div>
      <div class="image_content">
        <%= image_tag object['starImage'], class: "planets-show-image" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer-menu">
  <%= link_to 'https://x.com/sima9z77407', target: '_blank' do %>
    <i class="fa-brands fa-square-x-twitter"></i>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="header-containar">
<%= image_tag "logo.png", class:"header-log" %>

  <div class="header-menu">
    <%= link_to root_path, class: "header-menu-link startButton" do %>
      <i class="material-icons-outlined">auto_awesome</i>トップページ
    <% end %>
    <%= link_to signs_path, class: "header-menu-link startButton" do %>
      <i class="material-icons-outlined">star_rate</i>星座図鑑
    <% end %>
    <%= link_to planets_path, class: "header-menu-link startButton" do %>
      <i class="material-icons-outlined">rocket</i>惑星図鑑
    <% end %>
    <%= link_to fortunes_path, class: "header-menu-link startButton" do %>
      <i class="material-icons-outlined">auto_awesome_motion</i>星占い
    <% end %>
  </div>
</div>

app/views/signs/index.html.erb
<div class="signs_containar">
  <div class="signs_title">
    <h2><i class="material-icons-outlined">star_rate</i>星座一覧</h2>
  </div>

  <%= form_with url: signs_path, method: :get, local: true do |form| %>
    <div class="signs_form">
      <%= form.text_field :search, value: params[:search], class:"signs_form_text" %>
      <%= form.submit "検索", class:"signs_form_button" %>
    </div>
  <% end %>

  <div class="signs_index">
    <% if @data.present? %>
      <% @data.each do |object| %>
      <p><%=link_to object['jpName'], sign_path(object['id']), class: "index-menu-link startButton" %></p>
      <% end %>
    <% else %>
      <p>検索結果がありません。</p>
    <% end %>
    <p class="dummy"></p>
    <p class="dummy"></p>
    <p class="dummy"></p>
  </div>
</div>

app/views/signs/show.html.erb
<div class="sign_detail">
  <% @data['results'].each do |object| %>
    <div class="sign_info">
      <div class="text_content">
        <div class="text_upper_part">
          <div class="text_upper_part_name">
            <h1><%= object['jpName'] %><span></h1>
            <h3><%= object['enName'] %></h3>
            <h3><%= object['ryaku'] %></h3>
          </div>
            <h4>【季節】 <%= object['season'] %></h4>
            <h4>【方角】 <%= object['direction'] %></h4>
            <h4>【高度】 <%= object['altitude'] %></h4>
            <p>※「水平線の下」と表示されている場合、現在観測できません。</p>
        </div>
        <div class="text_beneath">
          <p><%= object['content'] %></p>
          <% if object['origin']!="なし" %>
            <h4>【神話】</h4>
            <p><%= object['origin'] %></p>
          <% end %>
        </div>
        <%= link_to "wiki", "https://ja.wikipedia.org/wiki/#{object['jpName']}", class: "wiki_link" %>
        <%= link_to '戻る', request.referrer, class: "wiki_link startButton" %>
      </div>
      <div class="image_content">
        <%= image_tag object['starImage'], class: "signs-show-image" %>
      </div>
    </div>
  <% end %>
</div>

app/views/tops/top.html.erb
<div class="top-container">
  <div class="top-title">
    <%= image_tag "星の図鑑.png", class:"top-log" %>
  </div>

  <div class="constellations_that_can_be_observed_today_title">
    <h2><i class="material-icons-outlined">auto_awesome</i>現在見える星座</h2>
  </div>

  <div class="constellations_that_can_be_observed_today">
    <% @data['results'].each do |object| %>
      <p><%=link_to object['jpName'], sign_path(object['id']), class: "index-menu-link startButton" %></p>
    <% end %>
    <p class="dummy"></p>
    <p class="dummy"></p>
    <p class="dummy"></p>
  </div>
  <div class="cautionary_note">
    <p>※季節関係なくその時点で観測可能なすべての星座が出力されます。【季節】はその星座が目立つ季節を指します。</p>
  </div>

</div>